version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DATABASE}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
    depends_on:
      - mysql
    volumes:
      - .:/app # Monta el directorio actual (donde está docker-compose.yml) en /app dentro del contenedor

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Volumen persistente para los datos de la base de datos
      # ¡ATENCIÓN A ESTAS LÍNEAS!
      # Monta el archivo flask.sql directamente desde la raíz del proyecto
      - ./flask.sql:/docker-entrypoint-initdb.d/flask.sql
      # Si también usas init_user.sh y está en mysql_init/, necesitas montarlo aparte:
      - ./mysql_init/init_user.sh:/docker-entrypoint-initdb.d/init_user.sh

volumes:
  mysql_data: